apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: custom-metric-sd
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1
    kind: Deployment
    name: dummy-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Object
    object:
      metricName: foo
      targetValue: 20
      target:
        apiVersion: v1
        kind: Pod
        name: custom-metric-sd
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: custom-metric-sd
  name: custom-metric-sd
  namespace: default
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - ./direct-to-sd --metric-name=foo --metric-value=40 --pod-id=$(POD_ID)
    image: gcr.io/google-samples/sd-dummy-exporter:latest
    name: sd-dummy-exporter
    env:
    - name: POD_ID
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.uid
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dummy-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: dummy-deployment
  template:
    metadata:
      labels:
        k8s-app: dummy-deployment
    spec:
      containers:
      - name: long
        image: busybox
        command: ["/bin/sh",  "-c", "sleep 180000000"]
