apiVersion: v1
kind: PersistentVolume
metadata:
  name: gke-disk
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 60Gi
  gcePersistentDisk:
    fsType: ext4
    pdName: gke-disk
  persistentVolumeReclaimPolicy: Retain
